// newline/d3-visualizations/13-using-d3-with-react-js/src/Chart/Axis.jsx
import React from "react";
import PropTypes from "prop-types";
import * as d3 from "d3";
import { dimensionsPropsType } from "./utils";
import { useChartDimensions } from "./Chart";

const axisComponentsByDimension = {
  x: AxisHorizontal,
  y: AxisVertical
};
const Axis = ({ dimension, ...props }) => {
  const dimensions = useChartDimensions();
  const Component = axisComponentsByDimension[dimension];
  if (!Component) return null;

  return <Component {...props} dimensions={dimensions} />;
};

Axis.propTypes = {
  dimension: PropTypes.oneOf(["x", "y"]),
  dimensions: dimensionsPropsType,
  scale: PropTypes.func,
  label: PropTypes.string,
  formatTick: PropTypes.func
};

const formatNumber = d3.format(",");
Axis.defaultProps = {
  dimension: "x",
  scale: null,
  formatTick: formatNumber
};

export default Axis;

function AxisHorizontal({ dimensions, label, formatTick, scale, ...props }) {
  const numberOfTicks =
    dimensions.boundedWidth < 600
      ? dimensions.boundedWidth / 100
      : dimensions.boundedWidth / 250;
  const ticks = scale.ticks(numberOfTicks);
  return (
    <g
      className="Axis AxisHorizontal"
      transform={`translate(0, ${dimensions.boundedHeight})`}
      {...props}
    >
      <line className="Axis__line" x2={dimensions.boundedWidth} />
      {ticks.map((tick, i) => (
        <text
          key={tick}
          className="Axis__tick"
          transform={`translate(${scale(tick)}, 25)`}
        >
          {formatTick(tick)}
        </text>
      ))}
      {label && (
        <text
          className="Axis__label"
          transform={`translate(${dimensions.boundedWidth / 2}, 60)`}
        >
          {label}
        </text>
      )}
    </g>
  );
}

function AxisVertical({ dimensions, label, formatTick, scale, ...props }) {
  const numberOfTicks = dimensions.boundedHeight / 70;
  const ticks = scale.ticks(numberOfTicks);
  return (
    <g className="Axis AxisVertical" {...props}>
      <line className="Axis__line" y2={dimensions.boundedHeight} />
      {ticks.map((tick, i) => (
        <text
          key={tick}
          className="Axis__tick"
          transform={`translate(-16, ${scale(tick)})`}
        >
          {formatTick(tick)}
        </text>
      ))}
      {label && (
        <text
          className="Axis_label"
          style={{
            transform: `translate(-56px, %{ dimensions.boundedHeight / 2}px) rotate(-90deg)`
          }}
        >
          {label}
        </text>
      )}
    </g>
  );
}

// newline/d3-visualizations/14-using-d3-with-angular/src/app/chart/axis/axis.component.ts
import {
  Component,
  Input,
  ViewChild,
  ElementRef,
  SimpleChanges,
  OnChanges
} from "@angular/core";
import * as d3 from "d3";
import { DimensionsType, ScaleType } from "../../utils/types";

@Component({
  selector: "[appAxis]",
  templateUrl: "./axis.component.html",
  styleUrls: ["./axis.component.css"]
})
export class AxisComponent implements OnChanges {
  @Input() dimensions: DimensionsType;
  @Input() dimension: "x" | "y" = "x";
  @Input() scale: ScaleType;
  @Input() label: string;
  @Input() formatTick: (value: any) => string | number = d3.format(",");

  private ticks: Function[];

  @ViewChild("axis", { static: true }) axis: ElementRef;

  ngOnChanges(changes: SimpleChanges): void {
    this.updateTicks();
  }

  updateTicks() {
    if (!this.dimensions || !this.scale) return;

    const numberOfTicks =
      this.dimension == "x"
        ? this.dimensions.boundedWidth < 600
          ? this.dimensions.boundedWidth / 100
          : this.dimensions.boundedWidth / 250
        : this.dimensions.boundedHeight / 70;

    this.ticks = this.scale.ticks(numberOfTicks);
    // const yAxisGenerator = d3.axisLeft().scale(this.scale);
    // const yAxis = d3.select(this.axis.nativeElement).call(yAxisGenerator);
    // d3.select(this.axis.nativeElement);
  }
}

<!-- <svg:g #axis></svg:g> -->
<svg:g
  *ngIf="dimension == 'x'"
  class="x"
  attr.transform="translate(0, {{ dimensions.boundedHeight }})"
>
  <svg:line [attr.x2]="dimensions.boundedWidth"></svg:line>
  <svg:text
    *ngFor="let tick of ticks"
    class="tick"
    attr.transform="translate({{ scale(tick) }}, 25)"
  >
    {{ formatTick(tick) }}
  </svg:text>
  <svg:text
    *ngIf="label"
    class="label"
    attr.transform="translate({{ dimensions.boundedWidth / 2 }}, 60)"
  >
    {{ label }}
  </svg:text>
</svg:g>

<svg:g class="y" *ngIf="dimension == 'y'">
  <svg:line [attr.y2]="dimensions.boundedHeight"></svg:line>
  <svg:text
    *ngFor="let tick of ticks"
    class="tick"
    attr.transform="translate(-16, {{ scale(tick) }})"
  >
    {{ formatTick(tick) }}
  </svg:text>
  <svg:text
    *ngIf="label"
    class="label"
    [ngStyle]="{
      transform: [
        'translate(-56px, ',
        dimensions.boundedHeight / 2,
        'px) rotate(-90deg)'
      ].join('')
    }"
  >
    {{ label }}
  </svg:text>
</svg:g>
